In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('train.csv')

In [3]:
base.drop_duplicates()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
base.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
aux = True
cont = 0
while aux :
    cont = cont + 1
    if cont < base.columns.size:
        if pd.isnull(base[base.columns[cont]]).sum() > 0:
            base.drop(base.columns[cont], 1, inplace = True)
            cont = cont - 1
    else:
        aux = False

In [6]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

In [7]:
for i, column in enumerate (base.columns):
    if base[column].dtype == 'object':
        labelEncoder.fit(base[column])
        base[column] = labelEncoder.transform(base[column])

In [8]:
y = base.iloc[:, 61:62].values
x = base.iloc[:, 1:61].values

In [9]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
scaler_y = StandardScaler()

In [10]:
x = scaler_x.fit_transform(x)
y = scaler_y.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size=0.15, random_state=0)

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
x_treinamento = pca.fit_transform(x_treinamento)
x_teste = pca.transform(x_teste)
componentes = pca.explained_variance_ratio_

In [13]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf', C = 10.0)
regressor.fit(x_treinamento, y_treinamento)

C:\Users\caiqsilv\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\caiqsilv\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVR(C=10.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
score_treinamento = regressor.score(x_treinamento, y_treinamento)
score_teste = regressor.score(x_teste, y_teste)

In [15]:
print(f'Score treinamento = {score_treinamento}')
print(f'Score teste = {score_teste}')

Score treinamento = 0.9164140883891523
Score teste = 0.8913818389111382

In [16]:
previsoes = regressor.predict(x_teste)

In [17]:
y_teste = scaler_y.inverse_transform(y_teste)
previsoes = scaler_y.inverse_transform(previsoes)

In [18]:
print(f'Valor previsto {previsoes[0]}')
print(f'Valor real {y_teste[0]}')

Valor previsto 246998.07395525905
Valor real [200624.]

In [19]:
import pickle

In [20]:
pickle.dump(regressor, open('svr_persistence.sav', 'wb'))